### ISSUE TITLE
error using the plugin 

### ISSUE THREAD

**Issue by thilinadinith** [queenvictoria/ember-videojs#3]
when i used 
 ` {{video-js autoplay=true src=path}}
`

im getting an error 

> Uncaught Error: Compile Error: video-js is not a helper

**Comment by eelke** [comment]
@thilinadinith Did you restart the Ember server? This error usually shows up when installing an Ember addon in a secondary terminal window and not restarting the server.

**Comment by queenvictoria** [comment]
We need more detail here. Restarting the ember server has no doubt resolved your issue. Of not please reopen the issue.
