### ISSUE TITLE
`didInsertElement` will not update `src` on player 

### ISSUE THREAD

**Issue by hbrysiewicz** [queenvictoria/ember-videojs#5]
I don't believe `didInsertElement` is the correct lifecycle hook to use for this player. Components get reused in Ember, so if the user navigates to a different route within the app, also using the `videojs-player` component, but using a different `src` value, the video is not updated. 

Instead, I think `didRender` should be used to either init the player or update the value of the source video for the player.

**Comment by queenvictoria** [comment]
Merged the pull request.
